apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
spec:
 replicas: 2
 strategy: 
  type: RollingUpdate
  rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
 selector:
   matchLabels:
     tier: frontend
 template:
  metadata:
   labels:
    app: nginx
    tier: frontend
    environment: production
    track: blue
  spec:
   restartPolicy: Always
   containers:
   - name: nginx
     image: nginx:1.9.2
     env:
     - name: CONF_PROFILE
       valueFrom:
        configMapKeyRef:
          name: env-config
          key: profile
     - name: CONF_USERNAME
       valueFrom:
        secretKeyRef:
          name: test-secret
          key: username
     resources:
       requests:
         memory: 64Mi
         cpu: 250m
       limits:
         memory: 128Mi
         cpu: 500m
     ports:
     - containerPort: 80
     volumeMounts:         
     - name: pv-storage 
       mountPath: /cache
   volumes:
   -  name: pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
   
       