apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
    tier: frontend
    track: stable
    environment: production
spec:
  containers:
  - name: nginx
    image: nginx:1.9.1
    env:
    - name: CONF_PROFILE
      valueFrom:
        configMapKeyRef:
          name: env-config
          key: profile
    resources:
      limits:
        memory: 0.2Gi
    ports:
    - containerPort: 80
    volumeMounts:         
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}

