apiVersion: v1
kind: Pod
metadata:
  name: mynginxapp
  labels:
    name: myapp
spec:
  containers:
  - name: nginximg
    image: nginx:1.9.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
