apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer-deployment
  labels:
    env: local
    track: blue
spec:
  selector:
    matchLabels:
      app: portainer-container
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata: 
      labels:
        app: portainer-container
    spec:
      containers:
        - image: portainer/portainer
          name: portainer
          resources:
              limits:
                cpu: 500m
                memory: 0.5Gi
          ports:
            - containerPort: 9000
            - containerPort: 8000
          volumeMounts:
            - name: portainer-data
              mountPath: /data
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: portainer-data
          emptyDir:
              {}
        - name: docker-socket
          hostPath:
              path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: portianer-service
spec:
  type: NodePort
  selector:
      app: portainer-container
  ports:
  - nodePort: 31000
    port: 9000
    targetPort: 9000
