apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  selector:
    matchLabels: 
      type: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Mi
  