apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  selectors:
    matchLabel: 
      type: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Mi