apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
    matchExpressions:
    - { key: app, operator: In, values: [nginx] }
    - { key: environment, operator: NotIn, values: [nginx] }
  template:
    metadata:
      labels:
        tier: frontend
        app: nginx
        environment: frontend
    spec:
      containers:
      - name: nginx-from-rs
        image: nginx:1.9.1
        env:
        - name: CONF_PROFILE
          value: claims
        resources:
          requests:
            memory: 64Mi
            cpu: 250m
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 80
        volumeMounts:         
        - name: cache-volume
          mountPath: /cache
      volumes:
      - name: cache-volume
        emptyDir: {}