version: '3'
services:
  web:
    image: httpd
    ports:
      - 80:80
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - 24224:24224
      - 24224:24224/udp

  elasticsearch:
    image: elasticsearch:7.4.2
    container_name: "es01"
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  kibana:
    image: kibana:7.4.2
    ports:
      - 5601:5601